name: Pull Request Stats

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events for the main branch
  pull_request:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          period: 180
          charts: false
          sort-by: 'COMMENTS'
